Refactor; fix numbering, add code comments, restore table of contents
ChainSafe/chainbridge-docs pull request #28
Opened 2021-05-26 00:12 UTC by waymobetta

## Description
[Local](https://github.com/ChainSafe/chainbridge-docs/blob/main/docs/local.md) guide was improperly formatted, causing some cosmetic issues when viewing on the [Running Local Guide](https://chainbridge.chainsafe.io/local/).

Issues include:
1. Malformed Table of Contents (unusable)
2. Numbering on single line (unreadable)
3. Missing code comments

## Related Issue Or Context

Closes: #27 

## How Has This Been Tested? Testing details.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation

## Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [X] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2021-05-26 12:15 UTC, P1sar requested changes

2021-05-26 12:15 UTC, P1sar commented on docs/local.md
> +```zsh
why zsh?

2021-05-26 12:15 UTC, P1sar commented on docs/local.md
> +$ cb-sol-cli deploy --all --relayerThreshold 1
why did you add $ sign everywhere in code snippets? Isn't it for rendering math formulas?

2021-05-26 13:56 UTC, waymobetta commented on docs/local.md
> +$ cb-sol-cli deploy --all --relayerThreshold 1
Sometimes when reading command line snippets the `$` is found denoting the start of a command line prompt.
This can be removed

2021-05-26 14:00 UTC, waymobetta commented on docs/local.md
> +```zsh
Just because I was running the commands through zsh, but this can also be switched back to bash if needed for consistency

2021-05-28 11:23 UTC, P1sar approved these changes

2021-05-28 11:23 UTC, merged