Handlers migration guide
ChainSafe/chainbridge-docs pull request #35
Opened 2021-10-26 18:18 UTC by waymobetta

## Description

A guide is written to detail steps to be taken by a bridge admin in order to configure a new handler (custom erc20/721/generic) instead of the using one of the default handlers.

**Includes:**
- [x] overwrite existing resource registration; code: [adminSetResource (SOL)](https://github.com/ChainSafe/chainbridge-solidity/blob/master/contracts/Bridge.sol#L221)
- [x] migration (moneys)
- [x] gotchas?

**Questions:**
1. should this assume that the new custom handler is already deployed?
2. ~should bridge be paused during this migration?~
3. is token amount in [withdraw](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/admin/withdraw.go#L16) command in WEI?

## Related Issue Or Context

Closes: [#8](https://github.com/ChainSafe/chainbridge-project-backlog/issues/8)

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [x] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2021-11-03 21:28 UTC, waymobetta commented
High level review is ready, but I'd also like to perform all of these steps manually after `withdraw` command is implemented following [Solidity PR 416](https://github.com/ChainSafe/chainbridge-solidity/pull/416) to ensure that nothing is being missed.

Also I would like to update the guide to use real values for the code examples, such as correctly formatted contract/wallet addresses and real amount in WEI.

2021-11-05 12:35 UTC, P1sar requested changes
Everting  else looks good for me

2021-11-05 12:35 UTC, P1sar commented on docs/guides/handlers-migration-guide.md
> +3. Withdraw total token balance from HandlerA (old) into HandlerB (new)
Maybe it worth mentioning that withdrawal is only actual in terms that Handler was Burnable?

2021-11-05 12:35 UTC, P1sar commented on docs/guides/handlers-migration-guide.md
> +[Docs: Admin Pause](https://github.com/ChainSafe/chainbridge-core/blob/main/README.md#pause)
Please create issue to add pause/unpause CLI CMDs and make sure we added them on next sprint

2021-11-05 20:28 UTC, waymobetta commented on docs/guides/handlers-migration-guide.md
> +3. Withdraw total token balance from HandlerA (old) into HandlerB (new)
I'm not understanding. Can you phrase differently please?

2021-11-08 02:21 UTC, waymobetta commented on docs/guides/handlers-migration-guide.md
> +3. Withdraw total token balance from HandlerA (old) into HandlerB (new)
I added some clarity to the docs based on your feedback

2021-11-08 02:22 UTC, waymobetta commented on docs/guides/handlers-migration-guide.md
> +[Docs: Admin Pause](https://github.com/ChainSafe/chainbridge-core/blob/main/README.md#pause)
Cool, will create issues and add to next sprint

2021-11-08 08:51 UTC, P1sar commented on docs/guides/handlers-migration-guide.md
> +3. Withdraw total token balance from HandlerA (old) into HandlerB (new)
i think its ok now

2021-11-08 08:51 UTC, P1sar approved these changes

2021-11-08 08:51 UTC, merged